package io.github.stellhub.stellguard;

/** 认证结果原因。 */
public enum AuthenticationReason {
    AUTHENTICATED,
    AUTHENTICATION_DENIED,
    AUTHENTICATION_DENIED_BYPASSED,
    AGENT_UNAVAILABLE_FAIL_OPEN,
    AGENT_UNAVAILABLE_BLOCKED,
    AGENT_NOT_READY,
    AGENT_GRPC_UNAVAILABLE,
    AGENT_GRPC_TIMEOUT,
    CREDENTIAL_INVALID,
    CREDENTIAL_EXPIRED,
    TRUST_DOMAIN_MISMATCH,
    AUDIENCE_MISMATCH,
    SPIFFE_ID_MISMATCH,
    DNS_NAME_MISMATCH,
    SDK_CONFIGURATION_ERROR,
    SDK_ERROR
}
